### ISSUE TITLE
incompatibility with lagfixer plugin

### ISSUE THREAD

**Issue by URSFR** [datatags/UltraCosmetics#151] opened 2023-12-30 21:27 UTC
### Check if the issue is fixed in dev builds

- [ ] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. use /uc menu
2. choose pets
3. select pet

### What was supposed to happen?

summon the pet

### What happened instead?

in chat shows:
Cosmetics > You spawned (MOB)
Cosmetics > You despawned (MOB)

(MOB) means it happens with any mob

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.4.2-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper-364 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### What plugins do you have installed?

AggressiveAnimals, BlueSlimeCore, BoostedAudio, ChatBubbles, CombatLogX, CookMe, DatapackLoader, DeadlyDisasters, DecentHolograms, Dualhorse *ExteronChunkFreezer, FastChunkPregenerator, FasterPathways, FoodSpoilage, ItemJoin, LagFixer, LavaDamage, LibsDisguises, LuckPerms, MedievalFactions MultiSignBook, MythicMobs, NoTrades, OfflinePlayers, PlaceholderAPI, PlantNerfer, PlayerTrails, ProtocolLib, RealisticSeasons, Resurrection Revive, RHSignItem, RPCommands, SafeLoadingScreen, SimpleParrying, SternalBoard, Terra, ThirstBar, TradeSystem, UltraCosmetics ValhallaMMO, Weight-RPG

the plugin that makes the problems its LagFixer

### Are there any errors in the console or in logs?

```
Could not pass event InventoryClickEvent to UltraCosmetics v3.4.2
java.lang.IllegalArgumentException: Entity cannot be null
	at be.isach.ultracosmetics.shaded.mobchip.ai.goal.Pathfinder.<init>(Pathfinder.java:23) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.ai.goal.CustomPathfinder.<init>(CustomPathfinder.java:16) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_20_R3.ChipUtil1_20_R3$3.<init>(ChipUtil1_20_R3.java:1348) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_20_R3.ChipUtil1_20_R3.custom(ChipUtil1_20_R3.java:1348) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_20_R3.ChipUtil1_20_R3.fromNMS(ChipUtil1_20_R3.java:1475) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_20_R3.ChipUtil1_20_R3.lambda$getGoals$0(ChipUtil1_20_R3.java:154) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at be.isach.ultracosmetics.shaded.mobchip.abstraction.v1_20_R3.ChipUtil1_20_R3.getGoals(ChipUtil1_20_R3.java:154) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.updateMap(BukkitAI.java:36) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.<init>(BukkitAI.java:31) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitBrain.getTargetAI(BukkitBrain.java:134) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.pets.Pet.clearPathfinders(Pet.java:130) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.pets.Pet.initializeEntity(Pet.java:113) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:89) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:106) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:168) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:66) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.menu.buttons.CosmeticButton.handleClick(CosmeticButton.java:112) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.menu.buttons.CosmeticButton.onClick(CosmeticButton.java:72) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:188) ~[UltraCosmetics-3.4.2-RELEASE.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor163.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-342]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-342]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-342]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3110) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-342]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-342]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Additional information that could be helpful in fixing the problem

The pets that are working even with lagfixer plugin enabled: Bat, Slime and magma cube

i dont know if its allowed to post the mod link
i didnt confirmed in latest dev build, it was missclick

**Comment by datatags** [comment] 2023-12-31 04:31
Looks like the issue is that LagFixer adds a dummy pathfinder to all mobs it touches, and MobChip doesn't recognize it. I've asked LagFixer to change this [here](https://www.spigotmc.org/threads/614192/page-4#post-4679913).

**Comment by datatags** [comment] 2024-01-30 19:51
Going to go ahead and close this since it's not something I can control, you may need to remind the LagFixer author to implement the fix though.

**Closed** 2024-01-30 19:51 UTC
Labels: bug, mobchip
